### ISSUE TITLE
Closing a staging repository

### ISSUE THREAD

**Issue by arkivanov** [nexus-actions/drop-nexus-staging-repo#1]
Hello! It would be nice to have a GitHub Action to close a staging repository. A use case: to validate the uploaded artifacts before releasing.

**Comment by romainbsl** [comment]
Hello :)
That's the job of the release action: https://github.com/nexus-actions/release-nexus-staging-repo
But at the moment, this closes the repo and wait until check passes before automatically release the version.

I guess we could add an option to just close the repo without auto-releasing it.

**Comment by romainbsl** [comment]
Made it possible here https://github.com/nexus-actions/release-nexus-staging-repo
with the option `close_only: 'true'`.

Not released yet, but can be tested on main branch, like:
`nexus-actions/release-nexus-staging-repo@main`

**Comment by arkivanov** [comment]
@romainbsl I tried the new flag but the action fails.

Run: https://github.com/arkivanov/Decompose/actions/runs/694853133

Configuration:
```
  close-staging-repository:
    name: Close staging repository
    runs-on: ubuntu-latest
    needs: [ metadata-publish, linux-publish, macos-publish ]
    steps:
      - name: Close staging repository
        uses: nexus-actions/release-nexus-staging-repo@main
        with:
          username: arkivanov
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staged_repository_id: ${{ needs.create_staging_repository.outputs.repository-id }}
          close_only: 'true'
```
